[platformio]
src_dir = ../..

[env:ch583]
platform = ch32v@1.1.0
board = genericCH583M
framework = none

build_src_filter =
    -<*>
    +<BLE/Peripheral/APP/>
    +<BLE/Peripheral/Profile/>
    +<BLE/Peripheral/Startup/>
    +<BLE/HAL/MCU.c>
    +<BLE/HAL/RTC.c>
    +<BLE/HAL/SLEEP.c>
    +<SRC/StdPeriphDriver/>
    +<SRC/RVMSIS/core_riscv.c>
    -<.git/>

board_build.ldscript = Ld/Link.ld

build_flags =
    -march=rv32imac
    -mabi=ilp32
    -msmall-data-limit=8
    -mno-save-restore
    -Os
    -ffunction-sections
    -fdata-sections
    -fstack-usage
    -fno-common
    -fsigned-char
    -fmessage-length=0
    -nostartfiles
    --specs=nano.specs
    --specs=nosys.specs
    -Wl,--gc-sections
    -Wl,--print-memory-usage
    -IAPP/include
    -IProfile/include
    -IStartup
    -I../../SRC/StdPeriphDriver/inc
    -I../HAL/include
    -I../LIB
    -I../../SRC/RVMSIS
    -L../LIB
    -L../../SRC/StdPeriphDriver
    -lCH58xBLE
    -lISP583
    -DDEBUG=1
    -DBLE_BUFF_MAX_LEN=251

extra_scripts = post:post_extra_script.py
upload_protocol = wch-link
debug_tool = wch-link
